### ISSUE TITLE
ambiguity="explicit" returns None

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#820]
**Describe the bug**

When I set ambiguity="explicit", it returns None when parsing. Not setting it makes it parse normally

**To Reproduce**

```py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Initial author: Bryan Hu.

The main program that will run.
"""
from pathlib import Path

import lark

here = Path(__file__).parent
lark_grammar = Path(here / "grammar.lark")

parser = lark.Lark(lark_grammar.read_text(), ambiguity="explicit")
DOC = R"""
func main (argv:List<Str>, argc: int) {
    obj Greeter {
        private var _name
        var name: property<Str>
        func init(name: str) -> Void {
            self._name = name
            self.name = property(
                get=(func() -> Str {return self._name})
            )
        }
        func __str__() -> Str {
            return "hello, " + self._name
        }
    }
    if not (len(argv) > 1) {
        print("You gotta give me a name")
    } else {
        var maing: Greeter = Greeter(argv[1])
        print(maing)
    }

}
"""
print(parser.parse(DOC).pretty())
```
And the very ambiguous, nondeterministic grammar (still trying to reduce ambiguity):
```lark
%import common.WS
%import common.NEWLINE
%import common.CNAME -> IDENTIFIER
%import python.STRING
%import common.SIGNED_NUMBER -> NUMBER
%import common.SH_COMMENT -> COMMENT

%ignore WS
%ignore ";"
%ignore NEWLINE
%ignore COMMENT

start: _statement+
////////////////////////////////////////////////////////////////
_statement:  _definition | _operation | _ifs
////////////////////////////////////////////////////////////////
_definition: function_definition | class_definition | variable_definition
// FUNCTION //
function_definition: "func" IDENTIFIER "(" [_sequence{functype, ","}] ")" ["->" _type] braced_code
anonymous_func: "(" "func" "(" [_sequence{functype, ","}] ")" ["->" _type] braced_code ")"
// VARIABLE //
?variable_definition: ("var"|"const") IDENTIFIER ((":" _type) | ([":" _type] "=" value))
// CLASS //
class_definition: "obj" IDENTIFIER [":" NAMESPACABLE] class_code
class_code: "{" (class_defs | _statement)+ "}"

?class_defs: meth_def | class_var_def

?meth_def: [PRIVATE|PUBLIC] function_definition
class_var_def: [PRIVATE|PUBLIC] variable_definition

PRIVATE: "private"
PUBLIC: "public"
////////////////////////////////////////////////////////////////
_operation:  _binary | _logic | _misc | value
// BINARY //
_binary: add
       | sub
       | div
       | mul
       | bor
       | band
       | bnot
       | bxor
add: _bop{"+"}
sub: _bop{"-"}
div: _bop{"/"}
mul: _bop{"*"}
bor: _bop{"|"}
band: _bop{"&"}
bnot: "!" _operation
bxor: _bop{"~"}
// LOGIC //
_logic: gt
      | lt
      | eq
      | not
      | and
      | or
gt: _bop{">"}
lt: _bop{"<"}
eq: _bop{"=="}
and: _bop{"and"}
or: _bop{"or"}
not: "not" _operation
// MISCELLANEOUS //
_misc: assign | return | index | call_op
assign: _bop{"="}
return: "return" [_sequence{value, ","}]
index: value "[" value "]"
call_op: (NAMESPACABLE|anonymous_func) "(" [arguments] ")"

//! PRIVATE !//
_bop{thing}: value thing _operation
arg.2: [IDENTIFIER "=" ] value
arguments: _sequence{arg, ","}  // To prevent clashing with assignment
// FILLER: "..."
////////////////////////////////////////////////////////////////
_ifs: if (elif)* else?
?if: "if" value braced_code
?elif: "else" if
?else: "else" braced_code
////////////////////////////////////////////////////////////////
?value: NAMESPACABLE
      | STRING
      | NUMBER
      | BOOLEAN
      | anonymous_func
      | paranthesised
      | _operation

NAMESPACABLE: /[a-zA-Z_]+(?:\.[0-9a-zA-Z_]+)*/
BOOLEAN: "true" | "false"

braced_code: "{" _statement+ "}" // TODO USE INDENT-BASED

_type: NAMESPACABLE | generic_type
generic_type: NAMESPACABLE "<" _type ">"
functype: (IDENTIFIER ":" _type) ["=" value]
paranthesised.2: "(" value ")"  // Will clash with call-op

_sequence{x, sep}: x (sep x)* sep?
``` 
Terminal output:
```traceback
Traceback (most recent call last):
  File "__main__.py", line 40, in <module>
    print(parser.parse(DOC).pretty())
AttributeError: 'NoneType' object has no attribute 'pretty'
```
If that is impossible, provide clear steps to reproduce the behavior.

**Comment by ThatXliner** [comment]
Poetry lock file (if useful): https://gist.github.com/ThatXliner/e900393295d8337e87acd2902734c484

**Comment by MegaIng** [comment]
(note, a mcve would be nice. This is a bit much to figure what is happeing)

Using git bisect, I found that this is related to #745 by @chanicpanic . Note that this wasn't a regression. Before that PR, this would error with index out of bounds, now it returns None.

This correctly indicates that there is an infinite ambiguity, which you can check by calling `lark.logger.setLevel('DEBUG')`, and passing `debug=True` to `Lark`. This infinite ambiguity is in this specific case between `value` and `_operation`. You should probably restructured your grammar to not contain this. But lark still shouldn't return `None`

**Comment by MegaIng** [comment]
Here a (I think) minimal example:

```
GRAMMAR = """
start: _operation
_operation:  value
value: "b"
      | "a" value
      | _operation
"""


parser = lark.Lark(GRAMMAR, ambiguity="explicit", debug =True)
print(parser.parse("ab"))
```

Observation: This works correctly when `start: value` is used instead. @ThatXliner that might also apply for you larger grammar, essentially keeping the infinite ambiguity, but not using `_operation` outside of `value`

**Comment by ThatXliner** [comment]
> This correctly indicates that there is an infinite ambiguity, which you can check by calling `lark.logger.setLevel('DEBUG')`, and passing `debug=True` to `Lark`. This infinite ambiguity is in this specific case between `value` and `_operation`. You should probably restructured your grammar to not contain this. But lark still shouldn't return `None`

Why not make it so when it *does* return None, raise an exception instead

**Comment by chanicpanic** [comment]
I have a fix for this. I'll open a PR shortly.

**Comment by erezsh** [comment]
@ThatXliner Please verify that latest `master` version fixes it.

**Comment by ThatXliner** [comment]
You fixed it. Yep.

> @ThatXliner Please verify that latest `master` version fixes it.
